import json
import boto3
import os
import urllib.parse
from datetime import datetime

# Initialize AWS clients
textract = boto3.client('textract')
dynamodb = boto3.resource('dynamodb')
s3 = boto3.client('s3')

# Get environment variables
DYNAMODB_TABLE = os.environ['DYNAMODB_TABLE']
table = dynamodb.Table(DYNAMODB_TABLE)

def lambda_handler(event, context):
    """
    Process documents uploaded to S3 using Amazon Textract
    Extract text and store metadata in DynamoDB
    """
    print(f"Document processor triggered: {json.dumps(event, indent=2)}")
    
    try:
        processed_count = 0
        
        # Process each S3 event record
        for record in event['Records']:
            bucket = record['s3']['bucket']['name']
            key = urllib.parse.unquote_plus(record['s3']['object']['key'], encoding='utf-8')
            
            print(f"Processing document: {key} from bucket: {bucket}")
            
            # Extract text using Textract
            textract_response = textract.detect_document_text(
                Document={
                    'S3Object': {
                        'Bucket': bucket,
                        'Name': key
                    }
                }
            )
            
            # Extract text content from Textract response
            extracted_text = []
            for block in textract_response['Blocks']:
                if block['BlockType'] == 'LINE':
                    extracted_text.append(block['Text'])
            
            full_text = '\n'.join(extracted_text)
            
            print(f"Extracted text length: {len(full_text)} characters")
            
            # Generate document ID from filename
            document_id = key.split('/')[-1].rsplit('.', 1)[0]  # Remove file extension
            
            # Store document metadata and extracted text in DynamoDB
            table.put_item(
                Item={
                    'PK': f'DOCUMENT#{document_id}',
                    'SK': 'METADATA',
                    'GSI1PK': 'DOCUMENT',
                    'GSI1SK': datetime.utcnow().isoformat(),
                    'documentId': document_id,
                    'documentKey': key,
                    'bucketName': bucket,
                    'extractedText': full_text,
                    'textLength': len(full_text),
                    'processedAt': datetime.utcnow().isoformat(),
                    'status': 'processed',
                    'fileSize': record['s3']['object']['size']
                }
            )
            
            print(f"Document metadata saved to DynamoDB: {document_id}")
            processed_count += 1
            
            # Optionally, trigger workflow for requirement analysis
            # This could create a new requirement based on the extracted text
            if 'requirement' in key.lower() or 'req' in key.lower():
                await_requirement_analysis(document_id, full_text)
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'Documents processed successfully',
                'processedCount': processed_count
            })
        }
        
    except Exception as error:
        print(f"Error processing document: {str(error)}")
        raise error

def await_requirement_analysis(document_id, extracted_text):
    """
    Analyze extracted text for potential requirements
    This is a placeholder for more sophisticated analysis
    """
    try:
        # Simple requirement detection logic
        lines = extracted_text.split('\n')
        potential_requirements = []
        
        for line in lines:
            line = line.strip()
            # Look for lines that might be requirements
            if (line.startswith(('REQ', 'Requirement', 'The system shall', 'User shall')) 
                and len(line) > 20):
                potential_requirements.append(line)
        
        if potential_requirements:
            # Create a draft requirement in DynamoDB
            requirement_id = f"REQ-{document_id}-{int(datetime.utcnow().timestamp())}"
            
            table.put_item(
                Item={
                    'PK': f'REQUIREMENT#{requirement_id}',
                    'SK': 'METADATA',
                    'GSI1PK': 'REQUIREMENT#DRAFT',
                    'GSI1SK': datetime.utcnow().isoformat(),
                    'requirementId': requirement_id,
                    'title': f'Auto-extracted from {document_id}',
                    'description': '\n'.join(potential_requirements[:3]),  # First 3 requirements
                    'sourceDocument': document_id,
                    'status': 'DRAFT',
                    'priority': 'MEDIUM',
                    'createdAt': datetime.utcnow().isoformat(),
                    'autoGenerated': True
                }
            )
            
            print(f"Created draft requirement: {requirement_id}")
    
    except Exception as e:
        print(f"Error in requirement analysis: {str(e)}")
        # Don't fail the main processing if requirement analysis fails